# Generated by Django 4.2.14 on 2024-07-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previewURL', models.URLField()),
                ('largeImageURL', models.URLField()),
                ('tags', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
